### PR TITLE
Geopy fix

### LINKED ISSUE #53: replace use of geopy vincenty with geodesic
Need to replace use of geopy vincenty with geodesic in the instance it is used in urbanaccess. vincenty is discontinued in geopy version 2.0 and replaced with geodesic with default projection WGS84.

Reference:
vincenty depreciation notice: https://geopy.readthedocs.io/en/stable/#geopy.distance.vincenty
geodesic: https://geopy.readthedocs.io/en/stable/#geopy.distance.geodesic

### PR DESCRIPTION
**Pull request by knaaptime**
`geopy` version 2 is out, so this resolves #53

### CODE REVIEW

**Comment by smmaurer** [comment]
Hi @knaaptime, thanks so much for this! And apologies for the slow response.

Substantively it looks perfect. Could you make a couple of formatting changes so that the `pycodestyle` tests pass?

1. change `<2` to `< 2` in L12

2. add one space to the indentation in L391

The Travis tests are running but are not showing up in GitHub for some reason: 
https://travis-ci.org/github/UDST/urbanaccess/builds/703587869

As far as I can tell, all the other errors are related to the OSMNet issue, so I think we can go ahead with merging and releasing this in parallel. cc @sablanchard

**Comment by knaaptime** [comment]
i can tack a fix for #60 onto this as well if its of interest? (the deperecation period is over so this raises a breaking error now)

**Comment by sablanchard** [comment]
Hi @knaaptime ! Responding to this: https://github.com/UDST/urbanaccess/pull/62#issuecomment-662165209 yes that would be great to also have a fix for that if you are interested in doing so. Instead of including it in this PR can you open a new PR for just that fix?

**Comment by knaaptime** [comment]
cool, will do

**Comment by sablanchard** [comment]
Hi @knaaptime @cvanoli has just made a PR to fix the depreciation issue here: https://github.com/UDST/urbanaccess/pull/65

**Pull request merged**
